### ISSUE TITLE
Builder::chunk may consider previously set offset and limit

### ISSUE THREAD

**Issue by vlakoff** [laravel/internals#103] opened 2016-05-28 20:14 UTC
Currently, if one does this:

``` php
DB::table('records')->offset(1000)->limit(500)->chunk(50, $callback);
```

He might expect to retrieve only the records from 1000 to 1500, but that's not the case: the whole table is retrieved. This is particularly surprising because other clauses such as `where` would be taken into consideration.

I have come with a first draft, not yet tested, and it still feels clumsy…

``` php
public function chunk($count, callable $callback)
{
    $thisOffset = $this->getOffset(); // method to be implemented
    $thisLimit = $this->getLimit(); // same

    $page = 1;
    $rowsfetched = 0;

    do {
        $skip = $thisOffset + ($page - 1) * $count;

        if ($thisLimit) {
            $remaining = $thisLimit - $rowsfetched;
            if ($remaining == 0) {
                return true;
            }
            $take = min($count, $remaining);
        } else {
            $take = $count;
        }

        $results = $this->skip($skip)->take($take)->get();
        $countResults = $results->count();

        if ($countResults == 0) {
            break;
        }

        // On each chunk result set, we will pass them to the callback and then let the
        // developer take care of everything within the callback, which allows us to
        // keep the memory low for spinning through large result sets for working.
        if (call_user_func($callback, $results) === false) {
            return false;
        }

        $page++;
        $rowsfetched += $countResults;
    }
    while ($countResults == $take);

    return true;
}
```

So,
- Do you agree on the idea?
- Suggestions for improving the code?

**Comment by JosephSilber** [comment] 2016-05-29 01:39
This has recently been tried, but has been shot down by Taylor as expected behavior.

**Comment by vlakoff** [comment] 2016-05-29 03:03
Yep, I've found it back: https://github.com/laravel/framework/pull/9681. It's not that recent… Funny how my code came close to arrilot's one.

**Comment by arrilot** [comment] 2016-05-29 12:23
@vlakoff there are not many other way :) I (and probably many others) still disagree with @taylorotwell in this case but he is the boss in the end

**Comment by taylorotwell** [comment] 2016-05-30 12:37
I will look into it again.

**Comment by vlakoff** [comment] 2016-05-31 00:21
Thanks :-)

Just a few reminders:
* Better check "`until count($results) < $chunk/take`", rather than "`while count($result) > 0`". This way, if the last chunk is partial, you know you have reached the end and don't do another query which returns no results. This could be applied to current code too.
* A case I had to keep in mind when working on the logic: if there is a `$limit` set and the last chunk is entire (not partial). Make sure you don't continue processing in this case.

**Comment by drmmr763** [comment] 2016-08-09 18:49
Just want to offer a friendly +1 for changing this. I literally just wrote the same lines expecting the chunk method to iterate over my given limit and offset values. It works perfectly with "whereBetween". 

thanks

**Comment by vlakoff** [comment] 2016-11-01 01:16
I've worked on a revised version which seems to be quite good. Already posting it here, if you want to have a glance at it:

```php
public function chunk($count, callable $callback)
{
    $offset = $this->getOffset() ?: 0; // method to be implemented
    $remaining = $this->getLimit(); // same

    do {
        if (! is_null($remaining)) {
            $limit = min($count, $remaining);
        } else {
            $limit = $count;
        }

        $results = $this->skip($offset)->take($limit)->get();

        $countResults = $results->count();

        if ($countResults == 0) {
            break;
        }

        // On each chunk result set, we will pass them to the callback and then let the
        // developer take care of everything within the callback, which allows us to
        // keep the memory low for spinning through large result sets for working.
        if (call_user_func($callback, $results) === false) {
            return false;
        }

        $offset += $countResults;

        if (! is_null($remaining)) {
            $remaining -= $countResults;
            if ($remaining == 0) {
                break;
            }
        }
    } while ($countResults == $limit);

    return true;
}
```

**Comment by vlakoff** [comment] 2016-11-17 12:16
Calling `chunk()` "pollutes" the `offset` and `limit` properties of the query builder instance. This might lead to side-effects if reusing the instance.

Would it be worth it to backup/restore these properties, or is it acceptable to consider the instance is "dirty" once the queries have been run?

**Comment by ISaidHey** [comment] 2017-01-24 15:24
Just chiming in with the need for this. Found this thread after writing limit()->chunk() logic and finding it not working.

**Comment by Kyle-J** [comment] 2017-02-01 00:38
+1 

Same issue here. Just came across a scenario expecting limit to work and am now trying to implement my own tick limit. It's easy to break out of because because it's a closure passed to an internal loop so `break` an `continue` don't work. If I use `exit` I can't output anything later so the only option is `return` and let it run it's course.

Anyone got a better way to break out of it?

`if($tick_count == $tick_limit) return;`

**Comment by alberto-bottarini** [comment] 2017-02-07 19:49
I've implemented a different approach:

        Builder::macro("chunkWithLimit", function ($count, $from, $to, callable $callback) {
            $page = 1;
            do {
                $offset = ($page - 1) * $count + $from;
                $results      = $this->offset($offset)->limit($count)->get();
                $countResults = count($results);
                if ($countResults == 0) {
                    break;
                }
                if ($callback($results) === false) {
                    return false;
                }
                $page++;
            } while ($countResults == $count && $offset < $to - $count);
            return true;
        });

Maybe this will be useful

**Comment by vlakoff** [comment] 2017-02-07 20:25
This approach is interesting, as using extra parameters instead of the offset/limit properties allows to simplify a bit the implementation.

Note your implementation has a flaw, it doesn't support partial pages. For example `chunkWithLimit(100, 0, 50)` would process 100 items instead of 50, `chunkWithLimit(100, 0, 150)` would process 200 items instead of 150.

<br>So, a macro could be a solution for now, but the ideal solution would still be to adapt the `chunk` methods.

My [snippet](https://github.com/laravel/internals/issues/103#issuecomment-257466880) above should be ready, but the boring part is updating the tests (mock skip/take instead of forPage) and adding new tests. If someone wants to take care of this, be my guest. I would be very grateful for this.

**Comment by DiederikvandenB** [comment] 2017-06-15 18:24
Regardless of whether the function should be adapted or not, I do believe the docs need to be clearer about this. Similar to many others, the expected behaviour would be for the function not to ignore any offset/limits. Just one extra sentence in the docs could've saved me some debugging.

**Comment by drbyte** [comment] 2017-06-16 04:22
@DiederikvandenB I'm sure a PR to the docs with that one extra sentence will be happily considered if it clarifies something that's lacking sufficient detail.

https://github.com/laravel/docs

**Comment by decadence** [comment] 2017-06-16 05:58
And it will not necessary be merged but you should give it a try

**Comment by hhsadiq** [comment] 2018-01-02 11:59
Facing same issue

**Comment by taylorotwell** [comment] 2018-03-09 16:15
If someone wants to PR a clean solution for this I would be open to considering it.

**Closed by taylorotwell** 2018-03-09 16:15 UTC

**Comment by andrewmclagan** [comment] 2018-03-18 22:58
Suffering this issue after writing an Elasticsearch queue indexer. Very *very* hard to debug.

**Comment by vlakoff** [comment] 2018-03-19 14:25
The new code I [posted above](https://github.com/laravel/ideas/issues/103#issuecomment-257466880) (wow, 2016) does work, but as I said in a [later comment](https://github.com/laravel/ideas/issues/103#issuecomment-278128952) (specifically, "mock skip/take instead of forPage"), the tedious part are the tests. I had given it a try, but it was getting incredibly verbose... and boring. Anyone willing to support?
