### ISSUE TITLE
[5.4] possible bug with pivot class

### ISSUE THREAD

**Issue by unstoppablecarl** [laravel/internals#390] opened 2017-01-27 15:25 UTC
Looking at the new pivot class functionality in 5.4
shouldn’t this function https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/MorphToMany.php#L129
be updated to return pivot model objects via `$this->uses` like it does here
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L378

**Comment by Garbee** [comment] 2017-01-27 17:18
Bugs go on the *Framework* repository. Internals is about new features or larger changes the community wants to happen in the framework.

**Comment by unstoppablecarl** [comment] 2017-01-31 16:49
I was not sure if it was a bug or not. If it was intended I thought further discussion would be more appropriate here. Should I post it in the framework too?

**Comment by Garbee** [comment] 2017-01-31 17:10
Just close this and make an issue on the framework repository. This is not really anything for discussion, it is up to Taylor to decide whether the functionality is working as intended or not.

**Closed** 2017-01-31 21:43 UTC
